server:
  port: 8130 # 服务端口

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 39.108.169.57:8848 # nacos服务地址
  servlet:
    multipart:
      max-file-size: 1024MB # 最大上传单个文件大小：默认1M
      max-request-size: 1024MB # 最大请求上传的数据大小 ：默认10M

aliyun:
  vod:
    keyId: LTAI4Fz2PZAZCvWCtNRayByB
    keySecret: 4mqfKHagS1K9Sm7hQXTppRA6rtZc2S
    templateGroupId: 123 #转码模板组id
    workflowId: 321 #工作流id

