spring:
  cloud:
    nacos:
      discovery:
        server-addr: 39.108.169.57:8848 # nacos服务地址
  #spring:
  redis:
    host: 39.108.169.57
    port: 6379
    database: 2
    password: hjh123 #默认为空
    lettuce:
      pool:
        max-active: 20  #最大连接数，负值表示没有限制，默认8
        max-wait: -1    #最大阻塞等待时间，负值表示没限制，默认-1
        max-idle: 8     #最大空闲连接，默认8
        min-idle: 0     #最小空闲连接，默认0

  datasource: # mysql数据库连接
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/confucius_uc?serverTimezone=GMT%2B8
    username: root
    password: 123456


wx:
  open:
    # 微信开放平台 appid
    appId: wxed9954c01bb89b47
    # 微信开放平台 appsecret
    appSecret: a7482517235173ddb4083788de60b90e
    # 微信开放平台 重定向url（guli.shop需要在微信开放平台配置）
    redirectUri: http://guli.shop/api/ucenter/wx/callback8160
