server:
  port: 8120 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: confucius-oss # 服务名
  #spring-cloud:
  cloud:
    nacos:
      discovery:
        server-addr: 39.108.169.57:8848 # nacos服务地址


aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    accessKeyId: LTAI4Fz2PZAZCvWCtNRayByB
    secretAccessKey: 4mqfKHagS1K9Sm7hQXTppRA6rtZc2S
    #bucket可以在控制台创建，也可以使用java代码创建，注意先测试bucket是否已被占用
    bucketName: confucius-bucket01


